# docker-compose.yml (e.g., for CI build step)
# 
# Generally not required just for building the extension. It's more useful if
# we need to run multiple services together (e.g., the extension build + a
# test server + a database). If we just need to build, use docker build.
services:
  build:
    build:
      context: .
      dockerfile: Dockerfile
      # Build up to the 'final' stage
      target: final 
    # The volume mount doesn't automatically extract these after
    # `docker compose build`.
    # 
    # We need to use the `docker cp`(check README) process to extract artifacts from
    # the built *image*. The volume mount is more useful if we were running
    # `docker compose up` and the container needed persistent storage or
    # access to host files during runtime.
    volumes:
      - ./build:/extension_build
    # command: ["tail", "-f", "/dev/null"] # Keep container running if needed
